from seed_data.seeder import Seeder
from spreadsheet_golf_tour_be.models.scores import Scores


class ScoresSeeder(Seeder):
    @classmethod
    def setup_seed_data(cls):
        from database import db

        if db.session.query(Scores).first() is None:
            scores = [
                Scores(
                    match_picks_id=1,
                    score=72,
                    round=1,
                ),
                Scores(
                    match_picks_id=1,
                    score=72,
                    round=2,
                ),
                Scores(
                    match_picks_id=1,
                    score=72,
                    round=3,
                ),
                Scores(
                    match_picks_id=1,
                    score=72,
                    round=4,
                ),
                Scores(
                    match_picks_id=2,
                    score=72,
                    round=1,
                ),
                Scores(
                    match_picks_id=2,
                    score=72,
                    round=2,
                ),
                Scores(
                    match_picks_id=2,
                    score=72,
                    round=3,
                ),
                Scores(
                    match_picks_id=2,
                    score=72,
                    round=4,
                ),
                Scores(
                    match_picks_id=9,
                    score=72,
                    round=1,
                ),
                Scores(
                    match_picks_id=9,
                    score=72,
                    round=2,
                ),
                Scores(
                    match_picks_id=9,
                    score=72,
                    round=3,
                ),
                Scores(
                    match_picks_id=9,
                    score=72,
                    round=4,
                ),
                Scores(
                    match_picks_id=10,
                    score=72,
                    round=1,
                ),
                Scores(
                    match_picks_id=10,
                    score=72,
                    round=2,
                ),
                Scores(
                    match_picks_id=10,
                    score=72,
                    round=3,
                ),
                Scores(
                    match_picks_id=10,
                    score=72,
                    round=4,
                ),
                Scores(
                    match_picks_id=17,
                    score=72,
                    round=1,
                ),
                Scores(
                    match_picks_id=17,
                    score=72,
                    round=2,
                ),
                Scores(
                    match_picks_id=17,
                    score=72,
                    round=3,
                ),
                Scores(
                    match_picks_id=17,
                    score=72,
                    round=4,
                ),
                Scores(
                    match_picks_id=18,
                    score=72,
                    round=1,
                ),
                Scores(
                    match_picks_id=18,
                    score=72,
                    round=2,
                ),
                Scores(
                    match_picks_id=18,
                    score=72,
                    round=3,
                ),
                Scores(
                    match_picks_id=18,
                    score=72,
                    round=4,
                ),
                Scores(
                    match_picks_id=25,
                    score=72,
                    round=1,
                ),
                Scores(
                    match_picks_id=25,
                    score=72,
                    round=2,
                ),
                Scores(
                    match_picks_id=25,
                    score=72,
                    round=3,
                ),
                Scores(
                    match_picks_id=25,
                    score=72,
                    round=4,
                ),
                Scores(
                    match_picks_id=26,
                    score=72,
                    round=1,
                ),
                Scores(
                    match_picks_id=26,
                    score=72,
                    round=2,
                ),
                Scores(
                    match_picks_id=26,
                    score=72,
                    round=3,
                ),
                Scores(
                    match_picks_id=26,
                    score=72,
                    round=4,
                ),
            ]
            db.session.bulk_save_objects(scores)
